### ISSUE TITLE
Make repo conform to recommended community standards

### ISSUE THREAD

**Issue by douira** [douira/resolution-editor#3]
Structure README file into sections:
- something general
- how to install (Windows/macOS/Linux)
- how to contribute
- how to file a bug (including the use of Imgur/similar service to share screenshots)
- code convention: look at the code already written and make it consistent

This also includes adding CONTRIBUTING and a code of conduct files. See here what all of this is about: https://opensource.guide/

- [x] https://opensource.guide/code-of-conduct/
- [x] https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines
- [x] better readme

**Comment by douira** [comment]
This also includes adding CONTRIBUTING and a code of conduct files. See here what all of this is about: https://opensource.guide/

- [ ] https://opensource.guide/code-of-conduct/
- [ ] https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines
- [ ] better readme

**Comment by douira** [comment]
Code of conduct is out of the scope of the current phase. (and really doesn't seem necessary to have with two people working on the project)

**Comment by douira** [comment]
added some basic contribution guidelines, they're not all-encompassing but pretty good for now.

**Comment by douira** [comment]
Added all things as required. Code of conduct was simply added with a template
